language: node_js

node_js:
  - 0.10

env:
  global:
    - SAUCE_USERNAME=angular-ci
    - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987

install:
  - npm install
  - npm install -g gulp
  - npm install -g karma-cli

before_script:

script:
  - karma start --single-run --browsers SL_Chrome --reporters dots

after_script:
